name: Generate Index Pages for All Rings

on:
  push:
    paths:
      - Ring_0/mods/**
      - Ring_1/mods/**
      - Ring_2/mods/**
      - Ring_3/mods/**

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: python -m pip install requests

      - name: Generate Index for Updated Rings
        run: |
          python <<EOF
          import requests
          import os
          import subprocess

          # Get the list of modified files
          modified_files = subprocess.check_output(
              "git diff-tree --no-commit-id --name-only -r ${{ github.sha }}",
              shell=True,
              text=True,
          ).strip().splitlines()

          # Extract unique "Ring_*/mods" directories from the modified files
          directories = set()
          for file in modified_files:
              if file.startswith("Ring_") and "mods/" in file:
                  directories.add("/".join(file.split("/")[:2]))

          for directory in directories:
              username = "${{ github.repository_owner }}"
              repository = "${{ github.event.repository.name }}"
              branch = "${{ github.ref_name }}"
              api_url = f"https://api.github.com/repos/{username}/{repository}/contents/{directory}?ref={branch}"
              response = requests.get(api_url, headers={"User-Agent": "GitHub-Action"})

              if response.status_code == 200:
                  files = response.json()
                  html_content = "<!DOCTYPE html>\\n<html>\\n<body>\\n<ul>\\n"
                  for file in files:
                      if file['type'] == 'file':
                          html_content += f'<li><a href="{file["name"]}">{file["name"]}</a></li>\\n'
                  html_content += "</ul>\\n</body>\\n</html>"
                  os.makedirs(directory, exist_ok=True)
                  with open(f"{directory}/index.html", "w") as f:
                      f.write(html_content)
              else:
                  raise Exception(f"Failed to fetch contents for {directory}: {response.status_code}, {response.text}")
          EOF

      - name: Commit Changes
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Ring_*/mods/index.html
          git commit -m "Update index.html files for modified Rings"
          git push
