name: Generate Index Page

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: python -m pip install requests  # Install Python requests library

      - name: Generate Index
        run: |
          python <<EOF
          import requests
          import os

          username = "${{ github.repository_owner }}"
          repository = "${{ github.event.repository.name }}"
          directory = ""  # Set this to the directory path you want to index
          branch = "${{ github.ref_name }}"
          api_url = f"https://api.github.com/repos/{username}/{repository}/contents/{directory}?ref={branch}"
          response = requests.get(api_url, headers={"User-Agent": "GitHub-Action"})
          if response.status_code == 200:
              files = response.json()
              html_content = "<!DOCTYPE html>\\n<html>\\n<head>\\n<title>Directory Listing</title>\\n</head>\\n<body>\\n"
              html_content += "<h1>Directory Listing</h1>\\n<ul>\\n"
              for file in files:
                  if file['type'] == 'file':
                      html_content += f'<li><a href="{file["download_url"]}">{file["name"]}</a></li>\\n'
              html_content += "</ul>\\n</body>\\n</html>"
              with open("index.html", "w") as f:
                  f.write(html_content)
          else:
              raise Exception(f"Failed to fetch contents: {response.status_code}, {response.text}")
          EOF

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update index.html"
          git push
